### PR TITLE
fix loadFont for v2 so VST doesn't crash

### PR DESCRIPTION
**Pull request by Torinbob**
Hi Sebastien,

I see you are working on your v2 branch of Bidoo which is great. I noticed you had not fixed the loadFont yet as required for v2 as outlined here:

https://vcvrack.com/manual/Migrate2#2-1-Don-t-store-Font-and-Image-references-across-multiple-frames

Without this fix, your v2 runs fine in v2 Standalone but immediately crashes the DAW when the Rack is run as a VST.

I have done the font fixes and when I compile my fork it runs fine as VST so I'm sending this pull request as it may save you a little time.

Thanks for your great modules!

Best,
Steve

### CODE REVIEW

**Comment by Coirt** [comment]
Is the crashing unrelated to the font? The font will simply be removed when you close the VST plugin window so it doesn't continually draw, when the window opens back up the font will be inserted again or should be using the recommended migration example. If no changes are made the font will be removed and not placed back, the migration example checks the font exists so when the window opens back up it is placed back on a module.

```
void draw(const DrawArgs& args) override {
	std::shared_ptr<Font> font = APP->window->loadFont(fontPath);
	if (font) {
		nvgFontFaceId(args.vg, font->handle);
		...
	}
}
```

`if (font)` is the check that the font exists, I believe; so when true it inserts the font again. I'm not too sure that the pull request does anything for fonts, it just adds an unnecessary line of code, you're creating a new variable to store the font as a string but the font is already a string. A better way to store the font would be to use a global variable that all the code can see.

`#define FONT APP->window->loadFont(asset::plugin(pluginInstance, "the font path"))`
or now in v2
`#define FONT "the font path"`

You only need to change this one line if you change fonts at a future point in time. It seems you still need the `std::string fontPath` though. I'm unsure if the `if` check is necessary. `std::string fontPath = FONT;` would be a good way to go here, imo.
 or 
```
...
std::string fontPath;

    yourWidget() {
	fontPath = asset::plugin(pluginInstance, FONT);
    }
```
with the smart point set up to `std::shared_ptr<Font> font = APP->window->loadFont(fontPath);`

**Comment by Torinbob** [comment]
I can't say exactly why, it's a bit weird for sure, but the crashing was 100% related to the previous loadFont method. Before the changes I made were done, the DAW would crash on startup every time if Bidoo was in the plugins folder (and if the file being opened used Rack VST). This was without any Bidoo modules even being used in the Rack VST patch as I could never get that far - just its mere presence in the plugins folder was enough. 

After making the changes, all is well and no crashing. Now happily using Bidoo in the VST. But if I revert just one cpp file back to how it was before, ANTN.cpp for example, and recompile, it crashes the DAW again on startup.

I agree that adding the if (font) is good practice and it would have been better to include it. 

Beyond that, I'm not a C++ developer so don't really want to get into technicalities - I wouldn't be surprised if there were more elegant/efficient ways to do it than I have done. My purpose here was to turn it from a plugin which crashed my DAW to one that didn't and in that regard the changes I made were successful.

**Comment by Coirt** [comment]
There's a few more changes than just the paths in the PR though, I tested in the VST also and had no crashes - fonts also load correctly as is, so that's the reason for asking if the font is unrelated to the crashes.

**Comment by Torinbob** [comment]
> There's a few more changes than just the paths in the PR though

No, there isn't. The changes I made were all related to font paths - nothing else.

**Comment by pauliusuza** [comment]
I can confirm that the module crashes VCV v2

**Comment by sebastien-bouffier** [comment]
Hi, I pushed a new commit with few upgrades. I removed all font references since I only use default font. Please let me know if V2 is still crashing. Best

**Comment by Torinbob** [comment]
Hi Sebastien,

I have just built and given a very quick test and the Rack plugin is not crashing the DAW on startup like it was before when Bidoo is installed - which is a good sign! I'll keep playing with it and will let you know if I find any issues.

Thanks
Steve

**Pull request closed without merging**
